zenlog/urls.py
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.views.static import serve
from . import views
if getattr(settings, 'SSO_URL', False):
    admin.site.login = login_required(admin.site.login)


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^attachment/(?P<pk>\d+)/$', views.attachment, name='attachment'),
    url(r'^attachment/(?P<pk>\d+)/preview/$', views.preview, name='preview'),
    url(r'^ajax/log/$', views.ajax_log, name='ajax_log'),
    url(r'^api/$', views.api, name='api'),
    url(r'^api/readlog/$', views.api_readlog, name='api_readlog'),
    url(r'^api/disk/$', views.api_disk, name='api_disk'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^activitylog/', include('activitylog.urls', namespace='activitylog')),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico', permanent=False))
]

urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
]

templates/base.html
{% load pickertags %}{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Zenlog{% endblock title %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}{% endblock head %}
    {% load_css %}
    <style type="text/css">
    body{
        padding-top: 50px;
    }
    .hero-page {
        padding-top: 100px;
        padding-bottom: 20px;
    }
    .hero-page > h1 {
        text-align: center;
    }
    form.form-p label {
        min-width: 200px;
    }
    </style>
    <script src="//cdn.jsdelivr.net/sockjs/1.0.0/sockjs.min.js"></script>
    {% block css %}{% endblock %}
    {% block less %}{% endblock %}
    {% load_js %}
    {% block script %}{% endblock script %}
    {% block extra_head %}{% endblock %}
</head>
<body>
    {% block body %}
    <header>
        <nav class="navbar navbar-fixed-top navbar-default">
            {# <div class="container"> #}
                <div class="navbar-header">
                    <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand">Dashboard</a>
                </div>

                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" >
                        <li><a href="{% url 'index' %}">Console Log</a></li>
                        <li><a href="{% url 'activitylog:index' %}">Activity Log</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right" style="margin-right: 0;">
                        {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">{{ user }} <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                {% if user.is_superuser %}
                                    <li><a href="/admin/">Admin</a></li>
                                {% endif %}
                                <li class="divider"></li>
                                <li><a href="{% url 'accounts.logout' %}">Log out</a></li>
                            </ul>
                        </li>
                        {% else %}
                            <li><a href="/accounts/login/">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            {# </div> #}
        </nav>
    </header>
    {% endblock body %}
    {% block container %}{% endblock container %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<style>
    body {
        background-color: #111;
    }
    #viewport {
        padding-bottom: 62px;
    }
    .event {
        color: #ddd;
        padding: 0 15px;
        padding-left: 30px;
        text-indent: -15px;
        font-family: monaco,monospace,courier,'courier new','Bitstream Vera Sans Mono';
        line-height: 140%;
        font-size: 13px;
    }
    .project {
        color: rgb(37, 140, 205);
        background-color: #262626;
    }
    .tags {
        background-color: #262626;
    }
    .tags a{
        color: rgb(181, 137, 0);
    }
    .message {
        white-space: pre-wrap;
        word-wrap: break-word;
    }
    #footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 62px;
        background-color: #333;
    }
    #footer form {
        padding-top: 9px;
    }
    #footer label {
        color: #ddd;
    }
    #qProject {
        width: 120px;
    }
    #qTxt {
        width: 400px;
    }
    #limitTxt {
        width: 80px;
    }
    #searchBtn {
        width: 150px;
    }
</style>
{% endblock %}
{% block container %}
<div id="viewport">
    <ul id="logArea" class="list-unstyled">
            
        {% for log in logs %}
            <li class="event" data-id="{{ log.id }}">
                <time>{{ log.created_on|date:'M d H:i:s' }}</time>
                <span class="project">{{ log.project.name }}:</span>
                <span class="tags">{% for tag in log.tags.all %}<a href="#" class="tag">{{ tag }}</a>{% if not forloop.last %},{% endif %}{% endfor %}</span>
                <span class="message"><a href="?group_uid={{ log.group_uid }}"><span class="glyphicon glyphicon-tags" style="display: inline;"></span></a> {% if log.attachment %}<a href="{% url 'attachment' log.pk %}" target="_blank"><img src="{% static "images/attach.png" %}" /></a>{% endif %} {{ log.level }} {{ log.message }}</span>
            </li>
        {% endfor %}

    </ul>
</div>
<div id="footer">
    <form action="" class="form-inline">
        <div class="form-group">
            <input type="text" name="q_project" id="qProjectTxt" class="form-control" placeholder="Project" value="{{ q_project }}" />
        </div>
        <div class="form-group">
            <input type="text" name="q" id="qTxt" class="form-control" placeholder="Input keyword (seperated with comma)" value="{{ q }}" />
        </div>
        <div class="form-group">
            <input type="datetime" name="start_date" id="startDateTxt" class="form-control" placeholder="Start (Y-m-d H:m:s)" value="{% if start_date %}{{ start_date }}{% endif %}" />
        </div>
        <div class="form-group">
            <input type="datetime" name="stop_date" id="stopDateTxt" class="form-control" placeholder="Stop (Y-m-d H:m:s)" value="{% if stop_date %}{{ stop_date }}{% endif %}" />
        </div>
        <div class="form-group">
            <input type="text" name="limit" id="limitTxt" class="form-control" placeholder="Limit" value="{{ limit }}" />
        </div>
        <button id="searchBtn" class="btn btn-primary">Search</button>
        {# <a href="#" class="btn btn-danger">Purge</a> #}
    </form>
</div>
{% endblock container %}

{% block script %}
<script>
    var isRealtime = {% if is_realtime %}true{% else %}false{% endif %};
</script>
<script>

Array.prototype.contains = function(obj) {
    var i = this.length;
    while (i--) {
        if (this[i] === obj) {
            return true;
        }
    }
    return false;
};

    fetchSockLog = function() {
        var sock = new SockJS(':8080/ws/log');
        sock.onopen = function() {
            console.log('socket opened.');
            var latestID = $('.event:last').data('id');
            var data = {
                'latest_id': latestID,
                'project_name': '{{ q_project }}',
                'q': '{{ q }}',
            };
            sock.send(JSON.stringify(data));
        };
        sock.onmessage = function(e) {
            // console.log('message', e.data);
            var data = JSON.parse(e.data);

            if(data.error) {
                console.log(data.error);
            }

            if(data.success === undefined) {
                var isBottom = $(window).scrollTop() + $(window).height() == $(document).height();
                for(var index in data.logs) {
                    var log = data.logs[index];
                    appendLog(log);
                }
                if(isBottom) {
                    var height = $("#logArea")[0].scrollHeight;
                    // $('html,body').animate({ 'scrollTop': height+"px" });   
                    $('html,body').scrollTop(height);
                }
            }
            else {
                console.log('re-sending message.')
                var latestID = $('.event:last').data('id');
                var data = {
                    'latest_id': latestID,
                    'project_name': '{{ q_project }}',
                };
                sock.send(JSON.stringify(data));
            }
        };
        sock.onclose = function() {
            console.log('close');
        };

        // sock.close();
    };

    appendLog = function(log) {
        var tags = [];
        for(var tag_index in log.tags) {
            var tag = log.tags[tag_index];
            tags.push('<a href="#" class="tag">'+ tag +'</a>');
        }
        var attachment_html = '';
        if(log.attachment) {
            attachment_html = '<a href="' + log.attachment + '" target="_blank"><img src="{% static "images/attach.png" %}" /></a>';
        }
        var tags_html = '<span class="tags">' + tags.join() + '</span>';
        var html = '<li class="event" data-id="'+log.id+'">'+
        '<time>'+ log.created_on +'</time> '+
        '<span class="project">'+ log.project_name +':</span> ' +
        tags_html +
        ' <span class="message">' + attachment_html + ' ' + log.level +' '+ log.message +'</span>' +
        '</li>';
        $('#logArea').append(html);
    };

    fetchLog = function() {
        var latestID = $('.event:last').data('id');
        var params = {
            'latest_id': latestID,
        };
        var settings = {
            url: '/ajax/log/',
            data: params,
            success: function(data) {
                if(!data.success) {
                    if(data.type == 'login_required') {
                        window.location.href = '/accounts/login/';
                    }
                    return;
                }
                for(var index in data.logs) {
                    var log = data.logs[index];
                    var tags = [];
                    for(var tag_index in log.tags) {
                        var tag = log.tags[tag_index];
                        tags.push('<a href="#" class="tag">'+ tag +'</a>');
                    }
                    var tags_html = '<span class="tags">' + tags.join() + '</span>';
                    var html = '<li class="event" data-id="'+log.id+'">'+
                    '<time>'+ log.created_on +'</time> '+
                    '<span class="project">'+ log.project_name +':</span> ' +
                    tags_html +
                    ' <span class="message">' + log.level +' '+ log.message +'</span>' +
                    '</li>';
                    $('#logArea').append(html);
                }
            },
            complete: function() {
                fetchLog();
            },
            dataType: 'json',
        };
        $.ajax(settings);
    };

    $(function(){
        if(isRealtime) {
            fetchSockLog();
            // fetchLog();
        }
        $('html, body').animate({ scrollTop: $('#logArea').prop("scrollHeight") });

        $('body').on('click', '.tag', function(){
            var tagName = $(this).text();
            var qVal = $('#qTxt').val();
            if(!qVal) {
                $('#qTxt').val(tagName);
            }
            else {
                var vals = qVal.split(',');
                if(!vals.contains(tagName))
                    $('#qTxt').val(qVal + ',' + tagName);
            }
            return false;
        });
    });
</script>
{% endblock script %}

templates/preview.html
{% autoescape off %}{{ source }}{% endautoescape %}

templates/source.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<style>
    body {
        background-color: #ddd;
    }
    #viewport {
        padding-bottom: 62px;
    }
    .event {
        color: #ddd;
        padding: 0 15px;
        padding-left: 30px;
        text-indent: -15px;
        font-family: monaco,monospace,courier,'courier new','Bitstream Vera Sans Mono';
        line-height: 140%;
        font-size: 13px;
    }
    .project {
        color: rgb(37, 140, 205);
        background-color: #262626;
    }
    .tags {
        background-color: #262626;
    }
    .tags a{
        color: rgb(181, 137, 0);
    }
    .message {
        white-space: pre-wrap;
        word-wrap: break-word;
    }
    #footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        height: 62px;
        background-color: #333;
    }
    #footer form {
        padding-top: 9px;
    }
    #footer label {
        color: #ddd;
    }
    #qTxt {
        width: 400px;
    }
    #limitTxt {
        width: 80px;
    }
    #searchBtn {
        width: 150px;
    }
    h1 {
        border-bottom: 1px solid #888;
        margin-bottom: 5.5px;
        padding-bottom: 5px;
    }
    pre {
        background: none;
        border: 0;
    }
</style>
{% endblock %}
{% block container %}
<div id="viewport">
    <h1>
        {{ log.level }} {{ log.message }}
        <div class="pull-right"> 
            <a href="{% url 'preview' log.pk %}" class="btn btn-info">Preview</a> 
            <a href="{{ log.attachment.url }}" class="btn btn-primary">Download</a>
        </div>
    </h1>
    <pre>{{ source }}</pre>
</div>
{% endblock container %}

{% block script %}
{% endblock script %}